In [1]:
!pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [3]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [4]:
# Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [5]:
# tokenize
tokens = word_tokenize(document.lower())

In [6]:
# build vocab
vocab = {'<unk>':0}

for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)

vocab

{'<unk>': 0,
 'about': 1,
 'the': 2,
 'program': 3,
 'what': 4,
 'is': 5,
 'course': 6,
 'fee': 7,
 'for': 8,
 'data': 9,
 'science': 10,
 'mentorship': 11,
 '(': 12,
 'dsmp': 13,
 '2023': 14,
 ')': 15,
 'follows': 16,
 'a': 17,
 'monthly': 18,
 'subscription': 19,
 'model': 20,
 'where': 21,
 'you': 22,
 'have': 23,
 'to': 24,
 'make': 25,
 'payments': 26,
 'of': 27,
 'rs': 28,
 '799/month': 29,
 '.': 30,
 'total': 31,
 'duration': 32,
 '?': 33,
 '7': 34,
 'months': 35,
 'so': 36,
 'becomes': 37,
 '799': 38,
 '*': 39,
 '=': 40,
 '5600': 41,
 'approx': 42,
 'syllabus': 43,
 'we': 44,
 'will': 45,
 'be': 46,
 'covering': 47,
 'following': 48,
 'modules': 49,
 ':': 50,
 'python': 51,
 'fundamentals': 52,
 'libraries': 53,
 'analysis': 54,
 'sql': 55,
 'maths': 56,
 'machine': 57,
 'learning': 58,
 'ml': 59,
 'algorithms': 60,
 'practical': 61,
 'mlops': 62,
 'case': 63,
 'studies': 64,
 'can': 65,
 'check': 66,
 'detailed': 67,
 'here': 68,
 '-': 69,
 'https': 70,
 '//learnwith.campusx.i

In [7]:
len(vocab)

289

In [8]:
input_sentences = document.split('\n')

In [9]:
def text_to_indices(sentence, vocab):

  numerical_sentence = []

  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [10]:
input_numerical_sentences = []

for sentence in input_sentences:
  input_numerical_sentences.append(text_to_indices(word_tokenize(sentence.lower()), vocab))

In [11]:
len(input_numerical_sentences)

78

In [12]:
training_sequence = []
for sentence in input_numerical_sentences:

  for i in range(1, len(sentence)):
    training_sequence.append(sentence[:i+1])

In [13]:
len(training_sequence)

942

In [14]:
training_sequence[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [15]:
len_list = []

for sequence in training_sequence:
  len_list.append(len(sequence))

max(len_list)

62

In [16]:
training_sequence[0]

[1, 2]

In [17]:
padded_training_sequence = []
for sequence in training_sequence:

  padded_training_sequence.append([0]*(max(len_list) - len(sequence)) + sequence)

In [18]:
len(padded_training_sequence[10])

62

In [19]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)

In [20]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   1,   2,   3],
        [  0,   0,   0,  ...,   0,   4,   5],
        ...,
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287],
        [  0,   0,   0,  ..., 286, 287, 288]])

In [21]:
X = padded_training_sequence[:, :-1]
y = padded_training_sequence[:,-1]

In [25]:
X

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [26]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [22]:
class CustomDataset(Dataset):

  def __init__(self, X, y):
    self.X = X
    self.y = y

  def __len__(self):
    return self.X.shape[0]

  def __getitem__(self, idx):
    return self.X[idx], self.y[idx]

In [23]:
dataset = CustomDataset(X,y)

In [24]:
len(dataset)

942

In [25]:
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

In [47]:
class LSTMModel(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, 100)
    self.lstm = nn.LSTM(100, 150, batch_first=True)
    self.fc = nn.Linear(150, vocab_size)

  def forward(self, x):
    embedded = self.embedding(x)
    intermediate_hidden_states, (final_hidden_state, final_cell_state) = self.lstm(embedded)
    output = self.fc(final_hidden_state.squeeze(0))
    return output

In [48]:
model = LSTMModel(len(vocab))

In [49]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [50]:
model.to(device)

LSTMModel(
  (embedding): Embedding(289, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=289, bias=True)
)

In [51]:
epochs = 50
learning_rate = 0.001

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [52]:
# training loop

for epoch in range(epochs):
  total_loss = 0

  for batch_x, batch_y in dataloader:

    batch_x, batch_y = batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 167.0078
Epoch: 2, Loss: 148.0332
Epoch: 3, Loss: 134.2811
Epoch: 4, Loss: 121.6909
Epoch: 5, Loss: 109.0645
Epoch: 6, Loss: 97.4100
Epoch: 7, Loss: 86.1854
Epoch: 8, Loss: 76.5059
Epoch: 9, Loss: 67.6907
Epoch: 10, Loss: 59.6860
Epoch: 11, Loss: 52.4968
Epoch: 12, Loss: 46.2684
Epoch: 13, Loss: 40.4405
Epoch: 14, Loss: 35.5416
Epoch: 15, Loss: 31.4819
Epoch: 16, Loss: 27.5361
Epoch: 17, Loss: 24.1473
Epoch: 18, Loss: 21.5760
Epoch: 19, Loss: 19.1334
Epoch: 20, Loss: 17.1625
Epoch: 21, Loss: 15.4157
Epoch: 22, Loss: 14.0569
Epoch: 23, Loss: 12.8515
Epoch: 24, Loss: 11.6323
Epoch: 25, Loss: 10.6608
Epoch: 26, Loss: 10.1366
Epoch: 27, Loss: 9.1890
Epoch: 28, Loss: 8.6896
Epoch: 29, Loss: 8.2721
Epoch: 30, Loss: 7.8745
Epoch: 31, Loss: 7.4675
Epoch: 32, Loss: 7.0378
Epoch: 33, Loss: 6.7275
Epoch: 34, Loss: 6.3941
Epoch: 35, Loss: 6.1596
Epoch: 36, Loss: 5.9831
Epoch: 37, Loss: 5.9128
Epoch: 38, Loss: 5.5591
Epoch: 39, Loss: 5.3942
Epoch: 40, Loss: 5.2470
Epoch: 41, Loss: 5

In [55]:
# prediction

def prediction(model, vocab, text):

  # tokenize
  tokenized_text = word_tokenize(text.lower())

  # text -> numerical indices
  numerical_text = text_to_indices(tokenized_text, vocab)

  # padding
  padded_text = torch.tensor([0] * (61 - len(numerical_text)) + numerical_text, dtype=torch.long).unsqueeze(0)
  padded_text = padded_text.to(device)

  # send to model
  output = model(padded_text)

  # predicted index
  value, index = torch.max(output, dim=1)

  # merge with text
  return text + " " + list(vocab.keys())[index]

In [56]:
prediction(model, vocab, "The course follows a monthly")

'The course follows a monthly subscription'

In [57]:
import time

num_tokens = 10
input_text = "hi how are"

for i in range(num_tokens):
  output_text = prediction(model, vocab, input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)

hi how are i
hi how are i am
hi how are i am not
hi how are i am not able
hi how are i am not able to
hi how are i am not able to make
hi how are i am not able to make the
hi how are i am not able to make the payment
hi how are i am not able to make the payment on
hi how are i am not able to make the payment on the


In [58]:
dataloader1 = DataLoader(dataset, batch_size=32, shuffle=False)

In [59]:
# Function to calculate accuracy
def calculate_accuracy(model, dataloader, device):
    model.eval()  # Set the model to evaluation mode
    correct = 0
    total = 0

    with torch.no_grad():  # No need to compute gradients
        for batch_x, batch_y in dataloader1:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)

            # Get model predictions
            outputs = model(batch_x)

            # Get the predicted word indices
            _, predicted = torch.max(outputs, dim=1)

            # Compare with actual labels
            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

# Compute accuracy
accuracy = calculate_accuracy(model, dataloader, device)
print(f"Model Accuracy: {accuracy:.2f}%")


Model Accuracy: 95.65%


In [32]:
x=nn.Embedding(289, 100)
y=nn.LSTM(100, 150, batch_first=True)

In [37]:
dataset[0][0].shape

torch.Size([61])

In [52]:
x(dataset[0][0].unsqueeze(0)).shape

torch.Size([1, 61, 100])

In [41]:
a,b=y(x(dataset[0][0].unsqueeze(0)))

In [42]:
a.shape

torch.Size([1, 61, 150])

In [44]:
c,d=b

In [46]:
c.shape,d.shape

(torch.Size([1, 1, 150]), torch.Size([1, 1, 150]))

In [47]:
a[0][-1]

tensor([ 0.0500,  0.0943,  0.4368,  0.0295,  0.0086, -0.1457,  0.2749,  0.0506,
         0.2300,  0.2222,  0.0321, -0.2498,  0.0755, -0.0030,  0.2244, -0.1892,
        -0.0975,  0.2826,  0.0928, -0.1633, -0.2447, -0.1124, -0.2857, -0.0433,
        -0.1585,  0.0739, -0.0289,  0.0014,  0.1486, -0.1719, -0.2588, -0.1133,
         0.2500, -0.1223, -0.1810,  0.1231, -0.1132,  0.0423,  0.2060, -0.1051,
        -0.1695,  0.1159, -0.3212,  0.0506,  0.0957,  0.0316, -0.2063,  0.0253,
         0.1494,  0.1713, -0.0311, -0.0133, -0.0245,  0.0625,  0.1262,  0.0163,
         0.1621,  0.0932,  0.2330, -0.1041,  0.0218, -0.1633, -0.0072, -0.1230,
         0.1054,  0.0753,  0.1634,  0.0815, -0.1057,  0.0716,  0.1764,  0.0365,
        -0.0605,  0.3678, -0.1129,  0.0063,  0.0919,  0.1118,  0.0103, -0.0525,
         0.0171, -0.0834, -0.0972, -0.2090, -0.1105,  0.1530, -0.0298,  0.0643,
         0.0835,  0.1295,  0.2125,  0.1813,  0.0097, -0.1405, -0.0186, -0.1697,
         0.2725,  0.0616,  0.0774, -0.16

In [48]:
c

tensor([[[ 0.0500,  0.0943,  0.4368,  0.0295,  0.0086, -0.1457,  0.2749,
           0.0506,  0.2300,  0.2222,  0.0321, -0.2498,  0.0755, -0.0030,
           0.2244, -0.1892, -0.0975,  0.2826,  0.0928, -0.1633, -0.2447,
          -0.1124, -0.2857, -0.0433, -0.1585,  0.0739, -0.0289,  0.0014,
           0.1486, -0.1719, -0.2588, -0.1133,  0.2500, -0.1223, -0.1810,
           0.1231, -0.1132,  0.0423,  0.2060, -0.1051, -0.1695,  0.1159,
          -0.3212,  0.0506,  0.0957,  0.0316, -0.2063,  0.0253,  0.1494,
           0.1713, -0.0311, -0.0133, -0.0245,  0.0625,  0.1262,  0.0163,
           0.1621,  0.0932,  0.2330, -0.1041,  0.0218, -0.1633, -0.0072,
          -0.1230,  0.1054,  0.0753,  0.1634,  0.0815, -0.1057,  0.0716,
           0.1764,  0.0365, -0.0605,  0.3678, -0.1129,  0.0063,  0.0919,
           0.1118,  0.0103, -0.0525,  0.0171, -0.0834, -0.0972, -0.2090,
          -0.1105,  0.1530, -0.0298,  0.0643,  0.0835,  0.1295,  0.2125,
           0.1813,  0.0097, -0.1405, -0.0186, -0.16

In [49]:
d

tensor([[[ 0.3040,  0.1457,  0.6700,  0.0635,  0.0179, -0.3082,  0.4802,
           0.1200,  0.5147,  0.4154,  0.0728, -0.6057,  0.1810, -0.0053,
           0.3733, -0.3671, -0.2551,  0.6115,  0.1999, -0.4778, -0.5379,
          -0.2642, -0.5789, -0.0610, -0.2776,  0.1043, -0.0691,  0.0029,
           0.2941, -0.2654, -0.4763, -0.2162,  0.4469, -0.3400, -0.6305,
           0.2028, -0.2452,  0.1458,  0.6493, -0.1827, -0.4536,  0.2025,
          -0.5337,  0.1299,  0.3918,  0.0651, -0.5597,  0.0398,  0.3097,
           0.3291, -0.0950, -0.0437, -0.0473,  0.1814,  0.2876,  0.0376,
           0.3355,  0.2073,  0.4698, -0.1839,  0.0480, -0.2500, -0.0142,
          -0.2189,  0.1841,  0.1557,  0.2336,  0.1724, -0.1830,  0.1711,
           0.3553,  0.0667, -0.1281,  0.7436, -0.1657,  0.0099,  0.2242,
           0.1731,  0.0483, -0.1211,  0.0332, -0.2545, -0.1666, -0.3120,
          -0.2159,  0.3750, -0.0784,  0.1687,  0.1335,  0.3101,  0.4425,
           0.3445,  0.0208, -0.1806, -0.0289, -0.71

In [43]:
torch.tensor(text_to_indices(word_tokenize("i am a hero"),vocab)).shape

torch.Size([4])