In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


#Creating a tensor


In [ ]:
a=torch.empty(2,3)

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2, 3,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.3616, 0.9987, 0.1024],
        [0.9013, 0.7685, 0.5933]])

In [ ]:
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[3616445622929465956, 6067248292745456949, 3905247822722250289],
        [6499313511489351982, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])

#Tensor Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.1,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

#Mathematical operations

## 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x


tensor([[0.4889, 0.7420],
        [0.9774, 0.3469]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.2390, 0.5505],
        [0.9553, 0.1203]])

##2. Element wise operatio

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.8442, 0.4172, 0.4184],
        [0.4424, 0.4841, 0.7388]])
tensor([[0.4402, 0.0795, 0.3385],
        [0.5054, 0.1750, 0.7067]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4041, 0.0196, 0.0799],
        [0.4424, 0.1341, 0.0321]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

##3. Reduction operation

In [8]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 5., 9.],
        [1., 9., 1.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([16.,  5.])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4.5000, 4.5000, 1.5000])

In [ ]:
# median
torch.median(e)

tensor(2.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [9]:
# product
torch.prod(e)

tensor(2025.)

In [10]:
# standard deviation
torch.std(e)

tensor(3.5777)

In [11]:
# variance
torch.var(e)

tensor(12.8000)

In [12]:
# argmax
torch.argmax(e)

tensor(2)

In [13]:
# argmin
torch.argmin(e)

tensor(3)

##4. Matrix operations

In [20]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[1, 7, 8],
        [0, 5, 7]])
tensor([[7, 1],
        [0, 8],
        [5, 4]])


In [15]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[69, 27],
        [41, 55]])

In [17]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [22]:
torch.transpose(f, 0, 1)

tensor([[1, 0],
        [7, 5],
        [8, 7]])

In [21]:
f

tensor([[1, 7, 8],
        [0, 5, 7]])

In [26]:
torch.transpose(f,1,0)

tensor([[1, 0],
        [7, 5],
        [8, 7]])

In [27]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 4., 6.],
        [8., 6., 7.],
        [0., 2., 4.]])

In [28]:
# determinant
torch.det(h)

tensor(18.)

In [29]:
# inverse
torch.inverse(h)

tensor([[ 0.5556, -0.2222, -0.4444],
        [-1.7778,  1.1111,  0.7222],
        [ 0.8889, -0.5556, -0.1111]])

##5. Comparison operations


In [30]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 2, 5],
        [8, 5, 1]])
tensor([[1, 6, 3],
        [1, 4, 0]])


In [32]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

##6. Special functions

In [33]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 0., 3.],
        [2., 5., 7.]])

In [34]:
# log
torch.log(k)

tensor([[0.6931,   -inf, 1.0986],
        [0.6931, 1.6094, 1.9459]])

In [35]:
# exp
torch.exp(k)

tensor([[7.3891e+00, 1.0000e+00, 2.0086e+01],
        [7.3891e+00, 1.4841e+02, 1.0966e+03]])

In [36]:
# sqrt
torch.sqrt(k)

tensor([[1.4142, 0.0000, 1.7321],
        [1.4142, 2.2361, 2.6458]])

In [37]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.5000, 0.9526],
        [0.8808, 0.9933, 0.9991]])

In [38]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.5000, 0.0067, 0.0180],
        [0.5000, 0.9933, 0.9820]])

In [39]:
# relu
torch.relu(k)

tensor([[2., 0., 3.],
        [2., 5., 7.]])

##Inplace Operations

In [40]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.8445, 0.8275, 0.6806],
        [0.3469, 0.7196, 0.2276]])
tensor([[0.6685, 0.6260, 0.1974],
        [0.7793, 0.5403, 0.9026]])


In [41]:
m.add_(n)

tensor([[1.5130, 1.4535, 0.8780],
        [1.1263, 1.2598, 1.1302]])

In [42]:
m

tensor([[1.5130, 1.4535, 0.8780],
        [1.1263, 1.2598, 1.1302]])

In [43]:
n

tensor([[0.6685, 0.6260, 0.1974],
        [0.7793, 0.5403, 0.9026]])

In [44]:
m.relu_()

tensor([[1.5130, 1.4535, 0.8780],
        [1.1263, 1.2598, 1.1302]])

In [45]:
m

tensor([[1.5130, 1.4535, 0.8780],
        [1.1263, 1.2598, 1.1302]])

##Copying a Tensor

In [46]:
a = torch.rand(2,3)
a

tensor([[0.5991, 0.9146, 0.1034],
        [0.2907, 0.1773, 0.4592]])

In [47]:
b = a

In [48]:
a[0][0] = 0

In [49]:
a

tensor([[0.0000, 0.9146, 0.1034],
        [0.2907, 0.1773, 0.4592]])

In [50]:
b

tensor([[0.0000, 0.9146, 0.1034],
        [0.2907, 0.1773, 0.4592]])

In [51]:
id(a)

133372137657488

In [52]:
id(b)

133372137657488

In [53]:
b = a.clone()

In [55]:
a

tensor([[0.0000, 0.9146, 0.1034],
        [0.2907, 0.1773, 0.4592]])

In [56]:
b

tensor([[0.0000, 0.9146, 0.1034],
        [0.2907, 0.1773, 0.4592]])

In [57]:
a[0][0] = 10

In [58]:
a

tensor([[10.0000,  0.9146,  0.1034],
        [ 0.2907,  0.1773,  0.4592]])

In [59]:
b

tensor([[0.0000, 0.9146, 0.1034],
        [0.2907, 0.1773, 0.4592]])

In [60]:
id(a)

133372137657488

In [61]:
id(b)

133371855560944

#Tensor Operations on GPU

In [62]:
torch.cuda.is_available()

True

In [64]:
device=torch.device('cuda')

In [65]:
torch.rand((2,3),device=device)

tensor([[0.0823, 0.8128, 0.6117],
        [0.7771, 0.4859, 0.3879]], device='cuda:0')

In [66]:
a=torch.rand((2,3))

In [67]:
d=a.to(device)

In [68]:
b+5

tensor([[5.0000, 5.9146, 5.1034],
        [5.2907, 5.1773, 5.4592]])

In [71]:
# prompt: create 2 tensor of 1000*10000 size and do matrix multiplication on cpu and gpu and calculate time

import time

size = (1000, 10000)

# CPU
tensor1_cpu = torch.rand(size)
tensor2_cpu = torch.rand(size).T  # Transpose for valid matrix multiplication

start_time_cpu = time.time()
result_cpu = torch.matmul(tensor1_cpu, tensor2_cpu)
end_time_cpu = time.time()
cpu_time = end_time_cpu - start_time_cpu

print(f"CPU matrix multiplication time: {cpu_time:.4f} seconds")

if torch.cuda.is_available():
    # GPU
    device = torch.device('cuda')
    tensor1_gpu = torch.rand(size, device=device)
    tensor2_gpu = torch.rand(size, device=device).T  # Transpose for valid matrix multiplication

    start_time_gpu = time.time()
    result_gpu = torch.matmul(tensor1_gpu, tensor2_gpu)
    torch.cuda.synchronize() # Wait for GPU to finish computation
    end_time_gpu = time.time()
    gpu_time = end_time_gpu - start_time_gpu

    print(f"GPU matrix multiplication time: {gpu_time:.4f} seconds")
    print(f"Speedup: {cpu_time/gpu_time:.4f}")
else:
    print("GPU not available for matrix multiplication.")

CPU matrix multiplication time: 0.2424 seconds
GPU matrix multiplication time: 0.0075 seconds
Speedup: 32.4667


In [72]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [76]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [77]:
b=torch.rand(2,3,4)
b

tensor([[[0.4101, 0.8512, 0.8520, 0.2919],
         [0.6824, 0.7657, 0.4624, 0.0164],
         [0.9941, 0.9750, 0.6355, 0.7345]],

        [[0.0016, 0.8370, 0.9768, 0.3858],
         [0.1031, 0.8660, 0.9378, 0.6195],
         [0.7623, 0.7337, 0.4607, 0.4698]]])

In [78]:
b.permute(2,0,1)

tensor([[[0.4101, 0.6824, 0.9941],
         [0.0016, 0.1031, 0.7623]],

        [[0.8512, 0.7657, 0.9750],
         [0.8370, 0.8660, 0.7337]],

        [[0.8520, 0.4624, 0.6355],
         [0.9768, 0.9378, 0.4607]],

        [[0.2919, 0.0164, 0.7345],
         [0.3858, 0.6195, 0.4698]]])

In [80]:
# unsqueeze
c=torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [86]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0)

tensor([0.1923, 0.2650, 0.9145, 0.0997, 0.8790, 0.5901, 0.6382, 0.3410, 0.5163,
        0.0656, 0.4436, 0.4873, 0.4749, 0.3767, 0.8617, 0.4237, 0.2679, 0.9944,
        0.9641, 0.4574])

#Numpy and PyTorch

In [87]:
import numpy as np

In [89]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [92]:
b=a.numpy()

In [93]:
type(b)

numpy.ndarray

In [97]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [98]:
torch.from_numpy(c)

tensor([1, 2, 3])